
import {courses,matches} from './courses.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chat=message=>'https://wa.me/201050226476?text='+encodeURIComponent(message);
const scenes={
ielts:'<rect x="61" y="29" width="116" height="143" rx="8"/><path d="M91 29v-10h56v10M83 69h58M83 88h72M83 107h47M83 126h59"/><circle cx="180" cy="144" r="27"/><path d="M180 126v18l12 9"/>',
general:'<path d="M35 53h91v63H60l-25 20z"/><path d="M119 83h90v64h-24l-25 18v-18h-41z"/><path d="M52 75h55M52 91h38M137 105h53M137 122h37"/><circle cx="185" cy="47" r="13"/>',
writing:'<rect x="34" y="55" width="152" height="95" rx="9"/><path d="m34 60 76 55 76-55M34 150l55-48m97 48-55-48"/><path d="m165 44 10-10 23 23-10 10-23-23zm-5 5-34 34-5 19 19-5 34-34"/>',
speaking:'<rect x="31" y="31" width="177" height="100" rx="5"/><path d="M50 101l34-24 34 10 32-33 33 13M109 132v32m-32 0h64"/><circle cx="182" cy="142" r="16"/><path d="M157 187v-17c0-19 51-19 51 0v17M165 149l-17-20"/><path d="M58 47h49"/>',
interview:'<circle cx="64" cy="89" r="21"/><circle cx="177" cy="89" r="21"/><path d="M29 170v-35c0-30 70-30 70 0v35m44 0v-35c0-30 70-30 70 0v35M77 143h86M112 143v43"/><path d="M85 27h66v35h-22l-14 12V62H85zM98 43h7m11 0h7m11 0h5"/>'
};
function art(c){return '<svg class="course-illustration" viewBox="0 0 240 200" role="img" aria-label="'+escape(c.title)+' illustration"><rect width="240" height="200" rx="12" fill="#e7f0e6"/><circle cx="203" cy="36" r="32" fill="#d5ed98"/><g fill="#f7faf3" stroke="#176b3a" stroke-width="4" stroke-linecap="round" stroke-linejoin="round">'+scenes[c.art]+'</g></svg>';}
let category='All courses';
function render(){const list=courses.filter(c=>matches(c,category,$('#search').value));$('#course-grid').innerHTML=list.length?list.map(c=>'<article class="course-card">'+art(c)+'<div class="course-body"><span class="category">'+escape(c.level)+'</span><h3>'+escape(c.title)+'</h3><p class="course-summary">'+escape(c.description)+'</p><div class="card-bottom"><span>'+escape(c.duration)+'</span><button class="course-link" data-course="'+c.id+'">View course ↗</button></div></div></article>').join(''):'<p class="empty">No courses match your search.</p>';}
function showCourse(id){const c=courses.find(c=>c.id===id);if(!c)return;$('#course-detail').innerHTML=art(c)+'<p class="eyebrow">'+escape(c.level)+' · '+escape(c.duration)+'</p><h2>'+escape(c.title)+'</h2><p>'+escape(c.description)+'</p><h3>What we’ll focus on</h3><ul class="course-topics">'+c.topics.map(t=>'<li>'+escape(t)+'</li>').join('')+'</ul><div class="detail-actions"><a class="button" target="_blank" rel="noopener noreferrer" href="'+escape(chat('Hi Mira! I would like a quote for '+c.title+'. Please send a quotation valid for one month.'))+'">Get a quote — valid for a month</a><a class="button light" target="_blank" rel="noopener noreferrer" href="'+escape(chat('Hi Mira! I would like to book a free trial session for '+c.title+'.'))+'">Book a free trial session</a></div>';$('#course-dialog').showModal();}
$('.filters').innerHTML=['All courses','General English','Workshops','IELTS'].map((c,i)=>'<button class="filter '+(i===0?'active':'')+'" aria-pressed="'+(i===0)+'" data-category="'+c+'">'+c+'</button>').join('');
document.addEventListener('click',e=>{const c=e.target.closest('[data-course]');if(c)showCourse(c.dataset.course);const f=e.target.closest('[data-category]');if(f){category=f.dataset.category;document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===f);b.setAttribute('aria-pressed',String(b===f));});render();}const close=e.target.closest('.close');if(close)close.closest('dialog').close();});
$('#search').addEventListener('input',render);
const questions=[["She ___ to work every day.",["go","goes","going","gone"],1],["We ___ a meeting yesterday.",["have","has","had","having"],2],["There isn't ___ milk left.",["some","any","many","a"],1],["I've lived here ___ 2020.",["for","since","during","from"],1],["If it rains tomorrow, we ___ indoors.",["stay","stayed","will stay","would stayed"],2],["This report ___ by our team last week.",["prepared","was prepared","has prepare","is preparing"],1],["Could you tell me where ___?",["is the office","the office is","does the office","the office does"],1],["If I had more time, I ___ another language.",["learn","will learn","would learn","had learn"],2],["By the time we arrived, the meeting ___.",["starts","has started","had started","starting"],2],["Please find the revised proposal ___.",["attached","attaching","attachment","attach"],0],["Despite ___ tired, she finished the presentation.",["be","was","being","to be"],2],["Choose the most polite request.",["Send it now.","You must send the file.","Could you please send the file?","Why didn't you send it?"],2]];
const form=$('#placement-form');
form.innerHTML=questions.map((q,i)=>'<fieldset class="placement-question"><legend>'+(i+1)+'. '+escape(q[0])+'</legend>'+q[1].map((a,j)=>'<label><input type="radio" name="q'+i+'" value="'+j+'" required> '+escape(a)+'</label>').join('')+'</fieldset>').join('')+'<button class="button" type="submit">See my result ↗</button>';
form.addEventListener('submit',e=>{e.preventDefault();const answers=new FormData(form);const score=questions.reduce((n,q,i)=>n+(Number(answers.get('q'+i))===q[2]?1:0),0);const level=score<=3?'Beginner':score<=6?'Elementary':score<=9?'Intermediate':'Upper-intermediate or above';const result=$('#placement-result');result.hidden=false;result.innerHTML='<h3>Your result: '+score+' / '+questions.length+'</h3><p>Suggested starting point: <strong>'+level+'</strong>.</p><p>This short grammar and writing check gives an initial indication. A conversation with Mira is needed to assess speaking, listening and your overall level.</p><a class="button" target="_blank" rel="noopener noreferrer" href="'+escape(chat('Hi Mira! I scored '+score+'/'+questions.length+' on the free placement check. My suggested starting point is '+level+'. I would like to discuss my level and coaching.'))+'">Discuss my result on WhatsApp ↗</a>';result.scrollIntoView({behavior:'smooth',block:'start'});});
$('#year').textContent=new Date().getFullYear();render();
