import {courses,progress,matches} from './courses.js';
const $=s=>document.querySelector(s);
let state={enrolled:[],completed:{},bookings:[]};
try { const data=JSON.parse(localStorage.getItem('forma-english-learning')||'null'); if(data&&Array.isArray(data.enrolled)&&data.completed&&Array.isArray(data.bookings)){state={enrolled:data.enrolled.filter(id=>courses.some(c=>c.id===id)),completed:Object.fromEntries(courses.map(c=>[c.id,Array.isArray(data.completed[c.id])?data.completed[c.id].filter(i=>Number.isInteger(i)&&i>=0&&i<c.lessons.length):[]])),bookings:data.bookings.filter(b=>b&&typeof b.id==='string'&&courses.some(c=>c.id===b.course)&&typeof b.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(b.date)&&typeof b.time==='string'&&/^\d{2}:\d{2}$/.test(b.time))};} } catch {}
let category='All courses',activeCourse=null,toastTimer;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function save(){try{localStorage.setItem('forma-english-learning',JSON.stringify(state));}catch{toast('Browser storage is unavailable. Changes will last for this visit only.');}renderLearning();renderCourses();}
function renderCourses(){ const filtered=courses.filter(c=>matches(c,category,$('#search').value)); $('#course-grid').innerHTML=filtered.length?filtered.map(c=>`<article class="course-card"><div class="course-art ${c.color}"><span class="level">${c.level}</span><span class="symbol" aria-hidden="true">${c.icon}</span></div><div class="course-body"><span class="category">${c.category}</span><h3>${c.title}</h3><p class="teacher">With ${c.teacher}</p><div class="card-bottom"><span>◷ ${c.duration} · ${c.lessons.length} lessons</span><button class="course-link" data-course="${c.id}">${state.enrolled.includes(c.id)?'Continue':'View course'} ↗</button></div></div></article>`).join(''):'<p class="empty">No courses match your search. Try another keyword or category.</p>'; }
function renderLearning(){ $('#learning-count').textContent=state.enrolled.length; $('#my-courses').innerHTML=state.enrolled.length?state.enrolled.map(id=>{const c=courses.find(c=>c.id===id),p=progress(c,state.completed[id]);return `<article class="learning-row"><div><h3>${c.title}</h3><p>${c.teacher} · ${c.lessons.length} guided lessons</p></div><div class="progress-wrap"><progress max="100" value="${p}" aria-label="${c.title} progress"></progress><span>${p}% complete</span></div><button class="button small" data-course="${id}">${p===100?'Review lessons':'Continue learning'} ↗</button></article>`;}).join(''):'<div class="empty">Your next chapter is waiting. Enroll in a course to see your lessons and progress here.</div>'; $('#bookings').innerHTML=state.bookings.length?'<h3>Your demo session requests</h3>'+state.bookings.map(b=>`<div class="booking-row"><span><strong>${courses.find(c=>c.id===b.course).teacher}</strong> · ${escape(b.date)} at ${escape(b.time)} (local time)<br>${courses.find(c=>c.id===b.course).title} · Demo request, not confirmed</span><button class="course-link" data-cancel="${escape(b.id)}">Cancel request</button></div>`).join(''):''; }
const exercises=[["Write a short introduction: your name, where you live, and one interest. Say it aloud three times.", "Write three open questions you could ask a new friend. Practice answering each in two sentences.", "Choose a familiar topic. Say \"I think…\", give a reason using \"because\", and ask \"What do you think?\"", "Practice ordering a drink: \"Could I have a coffee, please?\" Then ask how much it costs."], ["Write three sentences about yesterday, three about your usual week, and three about tomorrow. Underline each verb.", "Write five sentences with a subject and a verb. Add a detail about when or where each action happens.", "Turn \"You work here\" into \"Do you work here?\" Write four more present-simple questions using do or does.", "Compare \"She go to work\" with \"She goes to work\". Write five present-simple sentences about another person."], ["Compare \"ship\" and \"sheep\". Say each word slowly, then record yourself alternating between them.", "Practice these stress patterns: TAble, aBOUT, imPORtant. Say each word, making the stressed syllable clearer.", "Say \"an apple\" and \"turn off\" slowly, then smoothly. Practice connecting the final consonant to the next vowel.", "Record \"Could you help me, please?\" once slowly and once naturally. Listen for clarity and steady rhythm."], ["Prepare a 30-second introduction with your job, responsibilities, and one professional goal.", "Draft a short email asking to schedule a meeting. Include a greeting, purpose, proposed time, and polite closing.", "Practice \"Could I add something?\", \"I agree because…\", and \"Could you explain that?\" Use each in a short example.", "Prepare an answer to \"Tell me about yourself\". Include your experience, a relevant skill, and why you want the role."]];
function showCourse(id,open=true){activeCourse=courses.find(c=>c.id===id);const c=activeCourse,enrolled=state.enrolled.includes(id),completed=state.completed[id]||[];$('#course-detail').innerHTML=`<p class="eyebrow">${c.category} · ${c.level}</p><h2>${c.title}</h2><p>${c.description}</p><p><strong>${c.teacher}</strong> · ${c.role}<br>${c.duration} · ${c.lessons.length} self-paced lessons · Free demo</p><div class="detail-actions">${enrolled?`<span class="button light">Enrolled · ${progress(c,completed)}% complete</span>`:`<button class="button" id="enroll">Enroll for free ↗</button>`}<button class="button light" id="course-book">Book this mentor</button></div><h3>${enrolled?'Your lessons':'What you’ll practice'}</h3>${c.lessons.map((l,i)=>`<label class="lesson">${enrolled?`<input type="checkbox" data-lesson="${i}" ${completed.includes(i)?'checked':''} aria-label="Mark ${l} complete">`:`<span>${String(i+1).padStart(2,'0')}</span>`}<div><strong>${l}</strong><p>${enrolled?exercises[courses.indexOf(c)][i]:'Guided exercise · Learn at your own pace'}</p></div></label>`).join('')}<p class="demo-note">This starter curriculum contains short practice exercises. Video lessons and certificates are not included.</p>`;if(open)$('#course-dialog').showModal();}
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function openBooking(id){if($('#course-dialog').open)$('#course-dialog').close();$('#booking-form').reset();$('#booking-date').min=localDate();$('#booking-course').value=id||courses[0].id;$('#booking-error').textContent='';$('#booking-dialog').showModal();}
$('.filters').innerHTML=['All courses','Speaking','Grammar','Pronunciation','Business English'].map((c,i)=>`<button class="filter ${i===0?'active':''}" aria-pressed="${i===0}" data-category="${c}">${c}</button>`).join('');
$('#booking-course').innerHTML=courses.map(c=>`<option value="${c.id}">${c.title} — ${c.teacher}</option>`).join('');
document.addEventListener('click',e=>{const course=e.target.closest('[data-course]');if(course)showCourse(course.dataset.course);const filter=e.target.closest('[data-category]');if(filter){category=filter.dataset.category;document.querySelectorAll('.filter').forEach(b=>{b.classList.toggle('active',b===filter);b.setAttribute('aria-pressed',b===filter);});renderCourses();}if(e.target.closest('.close'))e.target.closest('dialog').close();if(e.target.closest('#enroll')){state.enrolled.push(activeCourse.id);state.completed[activeCourse.id]=[];save();showCourse(activeCourse.id,false);toast('You’re enrolled. Your next chapter starts here.');}if(e.target.closest('#course-book'))openBooking(activeCourse.id);const cancel=e.target.closest('[data-cancel]');if(cancel){state.bookings=state.bookings.filter(b=>b.id!==cancel.dataset.cancel);save();toast('Demo session request canceled.');}});
$('#course-detail').addEventListener('change',e=>{if(e.target.matches('[data-lesson]')){const id=activeCourse.id,i=Number(e.target.dataset.lesson),done=state.completed[id]||[];state.completed[id]=e.target.checked?[...new Set([...done,i])]:done.filter(n=>n!==i);save();const indicator=$('#course-detail .detail-actions .light');indicator.textContent=`Enrolled · ${progress(activeCourse,state.completed[id])}% complete`;if(progress(activeCourse,state.completed[id])===100)toast('All exercises complete. Keep growing!');}});
$('#search').addEventListener('input',renderCourses);$('#nav-book').onclick=()=>openBooking();$('#learning-book').onclick=()=>openBooking();
$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),date=data.get('date'),time=data.get('time');if(new Date(`${date}T${time}:00`)<=new Date()){$('#booking-error').textContent='Please choose a future date and time.';return;}state.bookings.push({id:crypto.randomUUID(),course:$('#booking-course').value,date,time});save();$('#booking-dialog').close();toast('Demo request saved locally. No email has been sent.');$('#learning').scrollIntoView({behavior:'smooth'});});
$('#year').textContent=new Date().getFullYear();renderCourses();renderLearning();
