import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('./', import.meta.url);
const files = { '/student-files/exams/Level-6-Exam.pdf':'student-files/exams/Level-6-Exam.pdf', '/student-files/exams/Level-5-Exam.pdf':'student-files/exams/Level-5-Exam.pdf', '/student-files/exams/Level-4-Exam.pdf':'student-files/exams/Level-4-Exam.pdf', '/student-files/exams/Level-3-Exam.pdf':'student-files/exams/Level-3-Exam.pdf', '/student-files/exams/Level-2-Exam.pdf':'student-files/exams/Level-2-Exam.pdf', '/student-files/exams/Level-1-Exam.pdf':'student-files/exams/Level-1-Exam.pdf', '/admin-calendar.js':'admin-calendar.js','/admin-calendar.css':'admin-calendar.css', '/images/vision-learners-4.png':'images/vision-learners-4.png', '/images/vision-learners-3.png':'images/vision-learners-3.png', '/images/vision-learners-2.png':'images/vision-learners-2.png', '/images/vision-learners-1.png':'images/vision-learners-1.png', '/images/home-teaching-coaching.png':'images/home-teaching-coaching.png', '/home-gallery.js':'home-gallery.js', '/mobile.css':'mobile.css', '/portal-access.js':'portal-access.js', '/admin-portal.js':'admin-portal.js', '/admin-clients.js':'admin-clients.js', '/portal-materials.js':'portal-materials.js', '/student-portal.js':'student-portal.js', '/portal-config.js':'portal-config.js', '/navigation.js':'navigation.js', '/placement-email.js':'placement-email.js', '/googlef6de591683171555.html':'googlef6de591683171555.html', '/placement-scoring.js':'placement-scoring.js', '/placement-config.js':'placement-config.js', '/placement-questions.js':'placement-questions.js', '/placement-test.pdf':'placement-test.pdf', '/speak-boldly-logo.png':'speak-boldly-logo.png', '/favicon.svg':'favicon.svg', '/':'index.html', '/index.html':'index.html', '/styles.css':'styles.css', '/app.js':'app.js', '/courses.js':'courses.js' };
const types = { pdf:'application/pdf', png:'image/png', svg:'image/svg+xml', html:'text/html',css:'text/css',js:'text/javascript' };
http.createServer(async (req,res) => {
  const name = files[new URL(req.url,'http://localhost').pathname];
  if (!name) { res.writeHead(404); return res.end('Not found'); }
  try { const body = await readFile(fileURLToPath(new URL(name,root))); res.writeHead(200,{'Content-Type':types[name.split('.').pop()]+'; charset=utf-8'}); res.end(body); }
  catch { res.writeHead(500); res.end('Unable to load page'); }
}).listen(Number(process.env.PORT || 3000),'0.0.0.0',()=>console.log('Forma running on port '+(process.env.PORT || 3000)));
